CREATE TABLE product(pid VARCHAR(100) PRIMARY KEY, name VARCHAR(100) NOT NULL, price INT NOT NULL, color VARCHAR(100) NOT NULL,size VARCHAR(100) NOT NULL, cid VARCHAR(100) NOT NULL);

CREATE TABLE catagory(cid VARCHAR(100) PRIMARY KEY, description VARCHAR(100) NOT NULL);

CREATE TABLE vendor(vid VARCHAR(100) PRIMARY KEY, description VARCHAR(100) NOT NULL);

CREATE TABLE stock(id INT PRIMARY KEY, cid VARCHAR(100) NOT NULL, vid VARCHAR(100) NOT NULL, quantity INT NOT NULL);